import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JitenshaSW - About',
  description: 'Generated by create next app'
}

export default function About() {
  return <div>About</div>
}
