import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JitenshaSW - Portfolio',
  description: 'Generated by create next app'
}

export default function Portfolio() {
  return <div>Portfolio</div>
}
