import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'JitenshaSW - Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body /* className={inter.className} */>
        <Navbar />
        <main className='flex flex-col items-center justify-between p-24'>
          {children}
        </main>
      </body>
    </html>
  )
}

const pages = [
  {
    path: '/',
    title: 'Home',
  },
  {
    path: '/portfolio',
    title: 'Portfolio',
  },
  {
    path: '/shop',
    title: 'Shop',
  },
  {
    path: '/commissions',
    title: 'Commissions',
  },
  {
    path: '/about',
    title: 'About',
  },
]

function Navbar() {
  return (
    <div className='navbar bg-base-300'>
      <div className='navbar-start'>
        <div className='dropdown'>
          <div tabIndex={0} role='button' className='btn btn-ghost lg:hidden'>
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='h-5 w-5'
              fill='none'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                d='M4 6h16M4 12h8m-8 6h16'
              />
            </svg>
          </div>
          <ul
            tabIndex={0}
            className='menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52'
          >
            {pages.map(page => (
              <li key={page.title}>
                <Link href={page.path}>{page.title}</Link>
              </li>
            ))}
          </ul>
        </div>
        <a className='btn btn-ghost text-xl'>JitenshaSW</a>
      </div>
      <div className='navbar-center hidden lg:flex'>
        <ul className='menu menu-horizontal px-1'>
          {pages.map(page => (
            <li key={page.title}>
              <Link href={page.path}>{page.title}</Link>
            </li>
          ))}
        </ul>
      </div>
      <div className='navbar-end'>
        <a className='btn btn-primary btn-sm btn-outline'>Button</a>
      </div>
    </div>
  )
}
