import type { Metadata } from 'next'
import { RedirectType, redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'JitenshaSW - Home',
  description: 'Generated by create next app',
}

export default function Home() {
  redirect('/shop', RedirectType.replace)

  // return <div>Hello</div>
}
