/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RoRcjPRmTd6
 */
import { CardContent, CardFooter, Card, CardTitle } from '@/components/ui/card'
import Image from 'next/image'
import { AspectRatio } from '@/components/ui/aspect-ratio'
import { EjunkieProduct } from '@/app/comics/schema'
import { DynamicRedirectButton } from './dynamic-redirect-button'

type Props = {
  comic: EjunkieProduct
}

export function ComicProductCard({ comic }: Props) {
  return (
    <Card className='w-full max-w-sm mx-auto overflow-auto overflow-x-hidden'>
      <AspectRatio className='mb-4' ratio={240 / 340}>
        <Image
          src={comic.images[0] ?? ''}
          alt={comic.name ?? ''}
          fill
          sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw'
          className='object-cover'
        />
      </AspectRatio>
      <CardContent className='text-center'>
        <div className='space-y-4'>
          <CardTitle className='text-xl font-semibold leading-6'>
            {comic.name ?? 'N/A'}
          </CardTitle>
          {/* <p className='text-sm leading-5 text-gray-500 dark:text-gray-400'>
            Jitensha
          </p> */}
          {/* <p className='text-sm leading-5'>{comic.details as string}</p> */}
          <div className='flex flex-wrap justify-center gap-2 mt-4 capitalize'>
            {comic.tags
              .filter(tag => tag !== null)
              .map(tag => (
                <span
                  key={tag}
                  className='text-xs bg-gray-200 text-gray-700 dark:bg-gray-800 dark:text-gray-300 px-2 py-1 rounded-full'
                >
                  {tag}
                </span>
              ))}
          </div>
        </div>
      </CardContent>
      <CardFooter className='flex justify-center'>
        <DynamicRedirectButton variant='outline' to={`/comics/${comic.id}`}>
          Read Now
        </DynamicRedirectButton>
      </CardFooter>
    </Card>
  )
}
