/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fdBLCaq4DGA
 */
import { Label } from "@/components/ui/label"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Button } from "@/components/ui/button"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function comic-product-page() {
  return (
    <div className="px-4 md:px-6 xl:px-8 py-6 lg:py-12">
      <div className="grid gap-6 md:gap-8 lg:grid-cols-[1fr_300px] lg:gap-12 xl:grid-cols-[1fr_350px_300px]">
        <div className="grid gap-4 md:gap-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              The Amazing Adventures of Captain Hyperdrive
            </h1>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-0.5">
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-primary" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              </div>
            </div>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center gap-2 text-sm">
              <TagIcon className="w-4 h-4 fill-primary" />
              <span className="text-gray-500 dark:text-gray-400">Superhero</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <TagIcon className="w-4 h-4 fill-primary" />
              <span className="text-gray-500 dark:text-gray-400">Adventure</span>
            </div>
          </div>
          <div className="grid gap-2 text-base lg:gap-4 xl:gap-6">
            <p>
              Captain Hyperdrive is the galaxy's greatest hero, fighting evil across the cosmos with courage and a
              trusty blaster. But when a new threat emerges from the shadows, he'll need all his wits and the help of
              some unlikely allies to save the day.
            </p>
          </div>
          <div className="grid gap-4 md:gap-6">
            <div className="flex items-center gap-2 text-sm">
              <CalendarIcon className="w-4 h-4 fill-muted" />
              <span className="text-sm text-gray-500 dark:text-gray-400">Published on June 23, 2023</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <DownloadIcon className="w-4 h-4 fill-muted" />
              <span className="text-sm text-gray-500 dark:text-gray-400">Includes PDF, ePub, and Kindle formats</span>
            </div>
          </div>
          <div className="grid gap-4 md:gap-6">
            <div className="grid gap-2">
              <Label className="text-base" htmlFor="color">
                Color
              </Label>
              <RadioGroup className="flex items-center gap-2" defaultValue="full" id="color">
                <Label
                  className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                  htmlFor="color-full"
                >
                  <RadioGroupItem id="color-full" value="full" />
                  Full Color
                </Label>
                <Label
                  className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                  htmlFor="color-bw"
                >
                  <RadioGroupItem id="color-bw" value="bw" />
                  B&W{"\n                              "}
                </Label>
              </RadioGroup>
            </div>
            <div className="grid gap-2">
              <Label className="text-base" htmlFor="format">
                Format
              </Label>
              <RadioGroup className="flex items-center gap-2" defaultValue="pdf" id="format">
                <Label
                  className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                  htmlFor="format-pdf"
                >
                  <RadioGroupItem id="format-pdf" value="pdf" />
                  PDF{"\n                              "}
                </Label>
                <Label
                  className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                  htmlFor="format-epub"
                >
                  <RadioGroupItem id="format-epub" value="epub" />
                  ePub{"\n                              "}
                </Label>
                <Label
                  className="border cursor-pointer rounded-md p-2 flex items-center gap-2 [&:has(:checked)]:bg-gray-100 dark:[&:has(:checked)]:bg-gray-800"
                  htmlFor="format-kindle"
                >
                  <RadioGroupItem id="format-kindle" value="kindle" />
                  Kindle
                </Label>
              </RadioGroup>
            </div>
          </div>
          <div className="grid gap-2 md:gap-4">
            <div className="text-2xl font-bold">$9.99</div>
            <Button size="lg">Buy Now</Button>
          </div>
        </div>
        <div className="grid gap-4 md:gap-6">
          <Carousel className="w-full max-w-sm aspect-video overflow-hidden rounded-xl border">
            <CarouselContent className="aspect-video">
              <CarouselItem>
                <img
                  alt="Cover"
                  className="object-cover aspect-video"
                  height={225}
                  src="/placeholder.svg"
                  width={400}
                />
              </CarouselItem>
              <CarouselItem>
                <img
                  alt="Cover"
                  className="object-cover aspect-video"
                  height={225}
                  src="/placeholder.svg"
                  width={400}
                />
              </CarouselItem>
              <CarouselItem>
                <img
                  alt="Cover"
                  className="object-cover aspect-video"
                  height={225}
                  src="/placeholder.svg"
                  width={400}
                />
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
          <div className="flex flex-col gap-2">
            <Button size="sm" variant="outline">
              Preview
            </Button>
            <Button size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
        <div className="grid gap-4 md:gap-6">
          <h3 className="text-xl font-bold">You might also like</h3>
          <div className="grid gap-4 md:gap-6 lg:grid-cols-2 xl:grid-cols-2 gap-y-0">
            <div className="flex gap-4">
              <img
                alt="Cover"
                className="aspect-[3/4] object-cover rounded-lg"
                height={180}
                src="/placeholder.svg"
                width={120}
              />
              <div className="grid gap-2.5">
                <h4 className="font-semibold tracking-tighter">The Intergalactic Adventures of Nebula Jones</h4>
                <p className="text-sm leading-none tracking-tight">by John J. Johnson</p>
                <Button size="sm">View</Button>
              </div>
            </div>
            <div className="flex gap-4">
              <img
                alt="Cover"
                className="aspect-[3/4] object-cover rounded-lg"
                height={180}
                src="/placeholder.svg"
                width={120}
              />
              <div className="grid gap-2.5">
                <h4 className="font-semibold tracking-tighter">The Secret of the Crystal Moon</h4>
                <p className="text-sm leading-none tracking-tight">by A. R. Adventure</p>
                <Button size="sm">View</Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function TagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z" />
      <path d="M7 7h.01" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function DownloadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}
