import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JitenshaSW - Commissions',
  description: 'Generated by create next app'
}

export default function Commissions() {
  return <div>Commissions</div>
}
