import { ComicProductCard } from '@/components/comic-product-card'
import type { Metadata } from 'next'
import { EjunkieProduct } from './schema'

export const metadata: Metadata = {
  title: 'JitenshaSW - Shop',
  description: 'Generated by create next app',
}

async function getProducts(): Promise<Record<string, unknown>> {
  const res = await fetch('https://api.e-junkie.com/api/153220/?page=1', {
    method: 'POST',
    body: require('querystring').stringify({
      key: process.env.EJUNKIE_API_KEY,
    }),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  })
  if (!res.ok) {
    throw new Error(res.statusText)
  }
  return res.json()
}

export default async function Shop() {
  const data = await getProducts()
  const products = data.products as EjunkieProduct[]

  console.log(products[0])

  return (
    <div>
      <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6'>
        {products.map(prod => (
          <ComicProductCard key={prod.id as string} comic={prod} />
        ))}
      </div>
    </div>
  )
}
