import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JitenshaSW - Shop',
  description: 'Generated by create next app',
}

export default function Shop() {
  return <div>Shop</div>
}
